language: cpp
sudo: false

# At some point, we will test specific combinations of options, but not all permutations, so we use explicit matrix.
matrix:

  include:

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - doxygen
        - python
        - mpich
        - libmpich-dev
        - libxml2-dev
        - libblas-dev
        - cmake
        - cmake-data
        - liblapack-dev
        - g++-6
        - gcc-6
    env:
      - GMX_MPI=OFF
      - GMX_THREAD_MPI=ON
      - gmxapi_DIR=$HOME/gromacs
      - GROMACS_DIR=$HOME/gromacs

# It is clearly a bad idea to have the development branch of a project requiring the development branch
# of another project in the primary build recipe. We either need to build and test development and master
# branches distinctly in a build matrix, only build off of tagged releases or the master branch of the
# dependency, or otherwise find a better solution that allows the master branch to be entirely included in
# the develop branch.
before_install:
  - uname -a
  - apt list --installed
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - wget https://github.com/kassonlab/gromacs-gmxapi/archive/dev_5.zip
  - unzip dev_5.zip

install:
  - pushd gromacs-gmxapi-dev_5
  - mkdir build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/gromacs -DGMX_FFT_LIBRARY=fftpack -DGMX_GPU=OFF -DGMX_OPENMP=OFF -DGMX_SIMD=None -DGMX_USE_RDTSCP=OFF -DGMX_MPI=$GMX_MPI -DGMX_THREAD_MPI=$GMX_THREAD_MPI ..
  - make -j4 install
  - popd
  - popd
  # pip 10.0.0 appears to be broken
  - python -m pip install --upgrade pip==9 --user
  - python -m pip install --upgrade setuptools --user
  - python -m pip install virtualenv --user
  - python -m pip install pytest --user
  - python -m pip install cmake --user
  - python -m pip install numpy --user
  - python -m pip install mpi4py --user
  - python -m pip install networkx --user

script:
  - GROMACS_DIR=$HOME/gromacs python -m pip install . --verbose --user
  - mpiexec -n 2 python -m mpi4py -m pytest --log-cli-level=DEBUG --pyargs gmx -s --verbose 

